### ISSUE TITLE
SwiftGen 설치 및 오류

### ISSUE THREAD

**Issue by JD-man** [JD-man/Friends#2]
# SwiftGen

1. Homebrew로 설치
2. 프로젝트에서 swiftgen.yml 파일 생성
3. yml 파일 내용 작성

```
input_dir: FriendWithSameHobby/Resources/Assets/
output_dir: FriendWithSameHobby/Resources/Assets/Generated

xcassets:
  inputs:
    - Images.xcassets
  outputs:
    - templateName: swift5
      params:
        forceProviedsNamespaces: true
        enumName: AssetsImages
      output: Assets+Images.swift
```
4. 터미널에서 swiftgen config lint를 사용해 Build Phase에 사용할 커맨드 얻기
    (이미 얻은 에셋에 대한 yml 내용은 주석처리해야함)
5. TARGETS의 Build Phases에서 스크립트 생성하고 위에서 얻은 커맨드 사용
6. 애플 실리콘에서는 경로 이슈가 있어서 스크립트에 아래를 추가해야함.
```
export PATH="$PATH:/opt/homebrew/bin"
```
